### ISSUE TITLE
Exception in Android release build - MissingPluginException(No implementation found for method subscribe

### ISSUE THREAD

**Issue by kattaliraees** [Lightstreamer/lightstreamer_flutter_client#1]
when running in release mode using `flutter run --release` getting below exception. In debug mode, it's working 

`lightstreamer_flutter_client v1.0.4`

![Screenshot 2023-05-02 at 1 53 58 PM](https://user-images.githubusercontent.com/574396/235647808-0993f278-13da-4637-b7dd-84bc1cf1d165.png)

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method subscribe on channel com.lightstreamer.lightstreamer_flutter_client.method)
E/flutter (24076): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:313)
E/flutter (24076): <asynchronous suspension>
E/flutter (24076): #1      LightstreamerFlutterClient.subscribe (package:lightstreamer_flutter_client/lightstreamer_flutter_client.dart:193)
E/flutter (24076): <asynchronous suspension>
```

**Comment by Bravo27** [comment]
Have you tried following the suggestions proposed [here](https://stackoverflow.com/questions/65872226/missingpluginexception-in-flutter-in-release-mode-android)?

**Comment by kattaliraees** [comment]
@Bravo27 Yes we tried that. by disabling progaurd settings and it worked. But we are using plenty of other plugins which have platform channels to Native Android/iOS code. wondering why the issue appears only for this plugin

**Comment by Bravo27** [comment]
I'm still not completely sure why Proguard excludes the plugin.
Another workaround that doesn't involve completely disabling Proguard optimizations is suggested in this issue ( #https://github.com/flutter/flutter/issues/78582), which involves providing Proguard with specific instructions to not ignore Lightstreamer classes, something like this:

```
-keep class com.lightstreamer.lightstreamer_flutter_client.** { ; }
-keep class com.lightstreamer.client.* { ; }
-keep class io.flutter.embedding.* { ; }
-keep class io.flutter.app.* { ; }
-keep class io.flutter.plugin.* { ; }
-keep class io.flutter.util.* { ; }
-keep class io.flutter.view.* { ; }
-keep class androidx.lifecycle.* { ; }
-keep class androidx.annotation.* { ; }
-keep class androidx.core.app.* { ; }
-keep class androidx.fragment.app.* { ; }
-keep class androidx.activity.* { *; }"
```

**Comment by kattaliraees** [comment]
Looks like the issue is gone in Flutter v3.10.0 release
