### ISSUE TITLE
Android build error android:attr/lStar not found in Flutter v3.24.2

### ISSUE THREAD

**Issue by kattaliraees** [Lightstreamer/lightstreamer_flutter_client#3]
Android build error after upgrading to Flutter version 3.24.2

We are using lightstreamer_flutter_client: ^1.0.4

We have also tried the latest v1.3.2 and the example project in both versions and the same error is coming.

## Error

```
* What went wrong:
Execution failed for task ':lightstreamer_flutter_client:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users/raeeskattali/Desktop/flutter/group_securities/build/lightstreamer_flutter_client/intermediates/merged_res/release/values/values.xml:194: AAPT: error: resource android:attr/lStar not found.
```

![Screenshot 2024-09-10 at 11 29 45 AM](https://github.com/user-attachments/assets/38cabf54-edee-4b34-b315-94baf9696337)

## Flutter environment
![Screenshot 2024-09-10 at 11 26 20 AM](https://github.com/user-attachments/assets/04bc2a32-03a0-4500-ba78-a695c3af7bf9)

**Comment by Bravo27** [comment]
Checking this error message, I found that it is often caused by the minimum Android SDK version settings for the project. Could you please check your settings for these project properties: compileSdkVersion and targetSdkVersion?

**Comment by kattaliraees** [comment]
@Bravo27 

compileSdkVersion 34
minSdkVersion 28
targetSdkVersion 33
Gradle version 7.5

**Comment by Bravo27** [comment]
Could you try with minSdkVersion >= 31? Otherwise please could you check out if one of the solutions proposed in [this StackOverflow thread](https://stackoverflow.com/questions/69033022/message-error-resource-androidattr-lstar-not-found) works for you?

**Comment by kattaliraees** [comment]
@Bravo27 I have already tried the stackoverlow solution and it didn't work. I just now tried increasing the minSdkVersion and that also didn't work. When I downgrade flutter back to 3.22.2, everything works without any changes. Have you tried to build the example flutter project in your repo using the latest flutter version?

**Comment by kattaliraees** [comment]
I have also tried creating a new flutter project and just added only lightstreamer flutter plugin in the pubspec.yaml and was able to re-produce the issue.

**Comment by Bravo27** [comment]
Ok @kattaliraees we'll try to reproduce the issue and let you know.

**Comment by kattaliraees** [comment]
@Bravo27 any update?

**Comment by Bravo27** [comment]
@kattaliraees sorry for the delay; we'll provide update as soon as possible.

**Comment by acarioni** [comment]
To reproduce your issue, I cloned the [Flutter Stock-List Demo](https://github.com/Lightstreamer/Lightstreamer-example-StockList-client-flutter) and updated Flutter to version 3.24.3. Initially, the build encountered a lot of errors. To resolve these, I ran the command `flutter pub get` and updated the `compileSdkVersion` and `targetSdkVersion` parameters to version 34 in the `build.gradle` file. After these changes, the demo launched without any errors.

Have you tried these steps? If your app still doesn't work, could you attempt to reproduce the errors using the Stock-List Demo? This might help us pinpoint the issue more effectively.

**Comment by kattaliraees** [comment]
I have cloned the Demo app and updated the build.gradle the same as our project(SDK versions). I was able to build on Flutter v3.22.2.

But after I upgraded flutter and it's not building. getting the same error

Are you using the latest version of Android Studio and Android toolchain? (as same as the one I showed using flutter doctor in my first comment here)

<img width="1507" alt="Screenshot 2024-09-17 at 9 24 36 PM" src="https://github.com/user-attachments/assets/5f75b92e-4c6b-4580-89a0-8399714fe99a">

**Comment by kattaliraees** [comment]
After checking https://github.com/flutter/flutter/issues/153281 

I added the below to android/build.gradle and it is building now (Both your Demo and our project)

```
subprojects {
    afterEvaluate { 
        android {
            compileSdkVersion 34
        }
    }
}
```

**Comment by acarioni** [comment]
Thank you for pointing out the fix. 

In the upcoming version of the Lightstreamer Client plugin, we will update the plugin's compileSdkVersion to version 34, eliminating the need for the current workaround.

In the meantime, here is the workaround suggested by the Flutter team to be placed in `android/build.gradle` (the new subproject block must precede any other subproject blocks):

```
subprojects {
    afterEvaluate { project ->
        if (project.extensions.findByName("android") != null) {
            Integer pluginCompileSdk = project.android.compileSdk
            if (pluginCompileSdk != null && pluginCompileSdk < 31) {
                project.logger.error(
                        "Warning: Overriding compileSdk version in Flutter plugin: "
                                + project.name
                                + " from "
                                + pluginCompileSdk
                                + " to 31 (to work around https://issuetracker.google.com/issues/199180389)."
                                + "\nIf there is not a new version of " + project.name + ", consider filing an issue against "
                                + project.name
                                + " to increase their compileSdk to the latest (otherwise try updating to the latest version)."
                )
                project.android {
                    compileSdk 31
                }
            }
        }
    }
}
```

(source: comments [2292201697](https://github.com/flutter/flutter/issues/153281#issuecomment-2292201697) and [2293071452](https://github.com/flutter/flutter/issues/153281#issuecomment-2293071452))
